bug #:
subject: cad/lepton-eda: Update to 1.9.15
attachment "description" field: cad/lepton-eda: Update to 1.9.15
submitted: 27 June 2021, 09:27
=============================================

Dear committers!

We are pleased to announce Lepton EDA release 1.9.15.
For the list of changes, please see the NEWS.md file:
https://github.com/lepton-eda/lepton-eda/blob/master/NEWS.md#notable-changes-in-lepton-eda-1915-20210626

Regards,
Dmitry.

