bug #: 264887
subject: cad/lepton-eda: Update to 1.9.18
attachment "description" field: cad/lepton-eda: Update to 1.9.18
URL field: https://github.com/lepton-eda/lepton-eda/blob/master/NEWS.md#notable-changes-in-lepton-eda-1918-20220529
submitted: 25 June 2022, 18:47
=============================================

Hello, dear committers!

We are glad to announce a new Lepton EDA release: 1.9.18.
Changelog:
https://github.com/lepton-eda/lepton-eda/blob/master/NEWS.md#notable-changes-in-lepton-eda-1918-20220529

The most notable change is that now we can pre-compile Guile
source files in advance (during the port build).
Using these .go files makes the startup time MUCH shorter.

Best regards,
Dmitry.

