bug #: 258433
subject: cad/lepton-eda: Update to 1.9.16
attachment "description" field: cad/lepton-eda: Update to 1.9.16
submitted: 11 September 2021, 17:05
=============================================

Greetings, dear committers!

We are glad to announce a new Lepton EDA release: 1.9.16.
For the list of notable changes, please take a look at the NEWS.md file:
https://github.com/lepton-eda/lepton-eda/blob/master/NEWS.md#notable-changes-in-lepton-eda-1916-20210731

Best regards,
Dmitry.

