bug #:
subject: cad/lepton-eda: Update to 1.9.14
attachment "description" field: cad/lepton-eda: Update to 1.9.14
submitted: 09 April 2021, xx:xx
=============================================

Greetings, dear committers!

Lepton EDA 1.9.14 is out.
For the list of changes, please see the NEWS.md file:
https://github.com/lepton-eda/lepton-eda/blob/master/NEWS.md#notable-changes-in-lepton-eda-1914-20210407

Curiously enough, I'm particularly pleased with
this release, though there are relatively few
"user-visible" changes.
IMO, most importantly, the repository has been
reorganized: we now have more uniform directory
structure, got rid of obsolete and ensure consistent
naming of existing files and dirs.
Now, I'm looking at it with satisfaction. :-)

It's not to say that we haven't made improvements
to the GUI: save buttons on tabs, more convenient
attributes editor dialog, revised interface of
lepton-attrib, for example, to name a few.

We also continue working on documentation. We've
started a dedicated web site for Lepton docs:
https://lepton-eda.github.io
And have a look at the updated wiki page with screenshots:
https://github.com/lepton-eda/lepton-eda/wiki/Screenshots

Regards,
Dmitry.

