bug #: 260790
subject: cad/lepton-eda: Update to 1.9.17
attachment "description" field: cad/lepton-eda: Update to 1.9.17
submitted: 29 December 2021, 12:00
=============================================

Greetings, dear committers!
Merry Christmas and happy New Year!

We are glad to announce a new Lepton EDA release: 1.9.17.
Notable changes:
https://github.com/lepton-eda/lepton-eda/blob/master/NEWS.md#notable-changes-in-lepton-eda-1917-20211219

Best regards,
Dmitry.

